### ISSUE TITLE
Cannot add to basic Xamarin.Forms project via nuget

### ISSUE THREAD

**Issue by mypark** [GuillaumeSalles/redux.NET#41]
New to Xamarin.forms and PCLs, and I'm trying to add via nuget to a Hello world xamarin.forms project when I get the following error:

`Could not install package 'Redux.NET 1.0.1'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
`

What framework do I need to target - and should I try to update the xamarin.forms starter project to that framework?

The only dependency I see in the .nuspec file is on System.Reactive 3.0.0 which I added already.

**Comment by GuillaumeSalles** [comment]
Hi @mypark,

Sorry for the delay. I was busy with other projects during the past few months...

I just released a new version of Redux.NET that target .NET standard 1.1. Maybe it will solve your case.

 https://www.nuget.org/packages/Redux.NET/2.0.0

Hope it helps

**Comment by helzgate** [comment]
I had to uninstall it because it it automatically tries to install the wrong version of system.reactive components compiled with PCL v5.0.  After uninstalling, I manually installed Reactive Extensions Main Library and manually picked version 3.0.0.  Then installed the latest version of Redux.Net with no issue.
